### ISSUE TITLE
Invalid usage of publishCreate()

### ISSUE THREAD

**Issue by sthzg** [lynnaloo/yacht-rock#8]
When posting new entries to the `GreatestHit` endpoint the console displays this error.

```
error: Invalid usage of publishCreate() :: Values must have an `undefined`, instead got ::
{ name: 'Foobar',
  artist: 'Bam',
  year: 1980,
  createdAt: Sat Mar 28 2015 19:26:19 GMT+0100 (CET),
  updatedAt: Sat Mar 28 2015 19:26:19 GMT+0100 (CET),
  id: 1 }
```

According to [this ticket](https://github.com/balderdashy/sails/issues/2105) it results from defining `id` as an attribute on the model. After removing it I got rid of the error and posting still works.

**Comment by tjwebb** [comment]
https://github.com/lynnaloo/yacht-rock/blob/master/api/models/GreatestHit.js#L12-L15

Don't need this `id` definition here. sails magically does this.
